<div class="social-footer">
<!-- If you want to remove this, please purchase "Remove powered by" package at http://magegiant.com/ -->
	<span>Powered by</span>
	<a href="http://magegiant.com/" target="_blank" rel="copyright">Magegiant</a>, 
	<a href="http://www.magentocommerce.com/magento-connect/one-step-checkout-22.html" target="_blank" title="Magento one step checkout">One step checkout</a> , 
	<a href="http://magegiant.com/magento-reward-points-extension/" title="Magento Reward Points">Magento Reward Points</a> , 
	<!-- <a href="http://www.magentocommerce.com/magento-connect/reward-points-10.html" title="Magento Reward Points">Magento Reward Points</a>,  -->
</div>